apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: arq
  namespace: flux-system
spec:
  interval: 5m0s
  targetNamespace: dev
  sourceRef:
    kind: GitRepository
    name: arq-repo
  path: ./deploy/k8s
  prune: true
  wait: true
  timeout: 5m0s