apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nats
  namespace: flux-system
spec:
  path: ./apps/nats
  prune: true
  interval: 10m
  wait: true
  targetNamespace: dev
  sourceRef:
    kind: GitRepository
    name: flux-system