apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-kafka
  namespace: flux-system
spec:
  path: ./apps/kafka
  prune: true
  interval: 10m
  wait: true
  targetNamespace: prod
  dependsOn:
    - name: kafka-operator
  sourceRef:
    kind: GitRepository
    name: flux-system