apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: strimzi-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://strimzi.io/charts
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-operator
  namespace: flux-system
spec:
  path: ./apps/kafka-operator
  prune: true
  interval: 10m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system