apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-operator
  namespace: flux-system
spec:
  path: ./apps/kafka-operator
  prune: true
  interval: 10m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system