apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: arq-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: arq-repo-pippin-pkey
  url: ssh://git@github.com/ej20002015/ARQ.git