apiVersion: v1
kind: Namespace
metadata:
  name: kafka-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi
  namespace: kafka-operator
spec:
  releaseName: strimzi
  interval: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.48.0
      sourceRef:
        kind: HelmRepository
        name: strimzi-charts
        namespace: flux-system
  values:
    watchAnyNamespace: true
  install:
    createNamespace: false