apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
spec:
  releaseName: nats
  interval: 5m
  chart:
    spec:
      chart: nats/nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  install:
    createNamespace: false